
include ../../Makefile.include

# path to store .obj, .cxx, and .so
MODULE := randgen

# swig module
SWIG_MODULE := esy_random

# python files to copy to module path
PYTHON_SRC := py_esy_random.py \
              __init__.py

include ../../Makefile.rule
