
include ../../Makefile.include

# path to store .obj, .cxx, and .so
MODULE := esynet

EXCLUDE_SRCFILE := esynet_config.cc \
                   esynet_interface.cc \
                   esynet_main1.cc \
                   esynet_random_unit.cc \
                   esy_foundation.cc 

# python files to copy to module path
PYTHON_SRC := esynet_main.py

include ../../Makefile.rule
