################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
.metadata/.plugins/org.eclipse.cdt.make.core \
.metadata/.plugins/org.eclipse.cdt.managedbuilder.core \
. \
hotspot \
libexo \
makedepend \
mcpat \
mcpat/cacti \
mcpat/cacti/obj_opt \
mcpat/obj_dbg \
testmpi \
testmpi/fft64 \
tests/src \
trapgen \
trapgen/io_less \
visualnoc/esynet \
visualnoc/esynet/orion_power_beta_mar2003/power \
visualnoc/integrator/define \
visualnoc/integrator \
visualnoc/integrator/moc \
visualnoc/integrator/modelsview \
visualnoc/integrator/obj \
visualnoc/integrator/qwt/designer/moc \
visualnoc/integrator/qwt/designer/obj \
visualnoc/integrator/qwt/designer \
visualnoc/integrator/qwt/designer/resources \
visualnoc/integrator/qwt/examples/animation \
visualnoc/integrator/qwt/examples/barchart \
visualnoc/integrator/qwt/examples/bode \
visualnoc/integrator/qwt/examples/controls \
visualnoc/integrator/qwt/examples/cpuplot \
visualnoc/integrator/qwt/examples/curvdemo1 \
visualnoc/integrator/qwt/examples/dials \
visualnoc/integrator/qwt/examples/distrowatch \
visualnoc/integrator/qwt/examples/event_filter \
visualnoc/integrator/qwt/examples/friedberg \
visualnoc/integrator/qwt/examples/itemeditor \
visualnoc/integrator/qwt/examples/legends \
visualnoc/integrator/qwt/examples/oscilloscope \
visualnoc/integrator/qwt/examples/radio \
visualnoc/integrator/qwt/examples/rasterview \
visualnoc/integrator/qwt/examples/realtime \
visualnoc/integrator/qwt/examples/refreshtest \
visualnoc/integrator/qwt/examples/scatterplot \
visualnoc/integrator/qwt/examples/simpleplot \
visualnoc/integrator/qwt/examples/sinusplot \
visualnoc/integrator/qwt/examples/spectrogram \
visualnoc/integrator/qwt/examples/stockchart \
visualnoc/integrator/qwt/examples/sysinfo \
visualnoc/integrator/qwt/examples/tvplot \
visualnoc/integrator/qwt/playground/curvetracker \
visualnoc/integrator/qwt/playground/graphicscale \
visualnoc/integrator/qwt/playground/plotmatrix \
visualnoc/integrator/qwt/playground/rescaler \
visualnoc/integrator/qwt/playground/scaleengine \
visualnoc/integrator/qwt/playground/shapes \
visualnoc/integrator/qwt/playground/svgmap \
visualnoc/integrator/qwt/playground/symbols \
visualnoc/integrator/qwt/playground/timescale \
visualnoc/integrator/qwt/src/moc \
visualnoc/integrator/qwt/src/obj \
visualnoc/integrator/qwt/src \
visualnoc/integrator/qwt/textengines/mathml \
visualnoc/integrator/subdialogs \
visualnoc/integrator/subwidgets \
visualnoc/integrator/threads \
visualnoc/interface \
visualnoc/qtparallel \
visualnoc/qtparallel/moc \
visualnoc/qtparallel/obj \
visualnoc/tinyxml \
visualnoc/trace2path \

