
include ../../Makefile.include

# path to store .obj, .cxx, and .so
MODULE := syscfg

# swig module
SWIG_MODULE := esy_syscfg

# python files to copy to module path
PYTHON_SRC := py_esy_syscfg.py \
              __init__.py

include ../../Makefile.rule
