################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../visualnoc/integrator/qwt/src/qwt_abstract_legend.cpp \
../visualnoc/integrator/qwt/src/qwt_abstract_scale.cpp \
../visualnoc/integrator/qwt/src/qwt_abstract_scale_draw.cpp \
../visualnoc/integrator/qwt/src/qwt_abstract_slider.cpp \
../visualnoc/integrator/qwt/src/qwt_analog_clock.cpp \
../visualnoc/integrator/qwt/src/qwt_arrow_button.cpp \
../visualnoc/integrator/qwt/src/qwt_clipper.cpp \
../visualnoc/integrator/qwt/src/qwt_color_map.cpp \
../visualnoc/integrator/qwt/src/qwt_column_symbol.cpp \
../visualnoc/integrator/qwt/src/qwt_compass.cpp \
../visualnoc/integrator/qwt/src/qwt_compass_rose.cpp \
../visualnoc/integrator/qwt/src/qwt_counter.cpp \
../visualnoc/integrator/qwt/src/qwt_curve_fitter.cpp \
../visualnoc/integrator/qwt/src/qwt_date.cpp \
../visualnoc/integrator/qwt/src/qwt_date_scale_draw.cpp \
../visualnoc/integrator/qwt/src/qwt_date_scale_engine.cpp \
../visualnoc/integrator/qwt/src/qwt_dial.cpp \
../visualnoc/integrator/qwt/src/qwt_dial_needle.cpp \
../visualnoc/integrator/qwt/src/qwt_dyngrid_layout.cpp \
../visualnoc/integrator/qwt/src/qwt_event_pattern.cpp \
../visualnoc/integrator/qwt/src/qwt_graphic.cpp \
../visualnoc/integrator/qwt/src/qwt_interval.cpp \
../visualnoc/integrator/qwt/src/qwt_interval_symbol.cpp \
../visualnoc/integrator/qwt/src/qwt_knob.cpp \
../visualnoc/integrator/qwt/src/qwt_legend.cpp \
../visualnoc/integrator/qwt/src/qwt_legend_data.cpp \
../visualnoc/integrator/qwt/src/qwt_legend_label.cpp \
../visualnoc/integrator/qwt/src/qwt_magnifier.cpp \
../visualnoc/integrator/qwt/src/qwt_math.cpp \
../visualnoc/integrator/qwt/src/qwt_matrix_raster_data.cpp \
../visualnoc/integrator/qwt/src/qwt_null_paintdevice.cpp \
../visualnoc/integrator/qwt/src/qwt_painter.cpp \
../visualnoc/integrator/qwt/src/qwt_painter_command.cpp \
../visualnoc/integrator/qwt/src/qwt_panner.cpp \
../visualnoc/integrator/qwt/src/qwt_picker.cpp \
../visualnoc/integrator/qwt/src/qwt_picker_machine.cpp \
../visualnoc/integrator/qwt/src/qwt_pixel_matrix.cpp \
../visualnoc/integrator/qwt/src/qwt_plot.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_abstract_barchart.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_axis.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_barchart.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_canvas.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_curve.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_dict.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_directpainter.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_glcanvas.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_grid.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_histogram.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_intervalcurve.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_item.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_layout.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_legenditem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_magnifier.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_marker.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_multi_barchart.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_panner.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_picker.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_rasteritem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_renderer.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_rescaler.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_scaleitem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_seriesitem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_shapeitem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_spectrocurve.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_spectrogram.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_svgitem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_textlabel.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_tradingcurve.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_xml.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_zoneitem.cpp \
../visualnoc/integrator/qwt/src/qwt_plot_zoomer.cpp \
../visualnoc/integrator/qwt/src/qwt_point_3d.cpp \
../visualnoc/integrator/qwt/src/qwt_point_data.cpp \
../visualnoc/integrator/qwt/src/qwt_point_mapper.cpp \
../visualnoc/integrator/qwt/src/qwt_point_polar.cpp \
../visualnoc/integrator/qwt/src/qwt_raster_data.cpp \
../visualnoc/integrator/qwt/src/qwt_round_scale_draw.cpp \
../visualnoc/integrator/qwt/src/qwt_sampling_thread.cpp \
../visualnoc/integrator/qwt/src/qwt_scale_div.cpp \
../visualnoc/integrator/qwt/src/qwt_scale_draw.cpp \
../visualnoc/integrator/qwt/src/qwt_scale_engine.cpp \
../visualnoc/integrator/qwt/src/qwt_scale_map.cpp \
../visualnoc/integrator/qwt/src/qwt_scale_widget.cpp \
../visualnoc/integrator/qwt/src/qwt_series_data.cpp \
../visualnoc/integrator/qwt/src/qwt_slider.cpp \
../visualnoc/integrator/qwt/src/qwt_spline.cpp \
../visualnoc/integrator/qwt/src/qwt_symbol.cpp \
../visualnoc/integrator/qwt/src/qwt_system_clock.cpp \
../visualnoc/integrator/qwt/src/qwt_text.cpp \
../visualnoc/integrator/qwt/src/qwt_text_engine.cpp \
../visualnoc/integrator/qwt/src/qwt_text_label.cpp \
../visualnoc/integrator/qwt/src/qwt_thermo.cpp \
../visualnoc/integrator/qwt/src/qwt_transform.cpp \
../visualnoc/integrator/qwt/src/qwt_wheel.cpp \
../visualnoc/integrator/qwt/src/qwt_widget_overlay.cpp 

OBJS += \
./visualnoc/integrator/qwt/src/qwt_abstract_legend.o \
./visualnoc/integrator/qwt/src/qwt_abstract_scale.o \
./visualnoc/integrator/qwt/src/qwt_abstract_scale_draw.o \
./visualnoc/integrator/qwt/src/qwt_abstract_slider.o \
./visualnoc/integrator/qwt/src/qwt_analog_clock.o \
./visualnoc/integrator/qwt/src/qwt_arrow_button.o \
./visualnoc/integrator/qwt/src/qwt_clipper.o \
./visualnoc/integrator/qwt/src/qwt_color_map.o \
./visualnoc/integrator/qwt/src/qwt_column_symbol.o \
./visualnoc/integrator/qwt/src/qwt_compass.o \
./visualnoc/integrator/qwt/src/qwt_compass_rose.o \
./visualnoc/integrator/qwt/src/qwt_counter.o \
./visualnoc/integrator/qwt/src/qwt_curve_fitter.o \
./visualnoc/integrator/qwt/src/qwt_date.o \
./visualnoc/integrator/qwt/src/qwt_date_scale_draw.o \
./visualnoc/integrator/qwt/src/qwt_date_scale_engine.o \
./visualnoc/integrator/qwt/src/qwt_dial.o \
./visualnoc/integrator/qwt/src/qwt_dial_needle.o \
./visualnoc/integrator/qwt/src/qwt_dyngrid_layout.o \
./visualnoc/integrator/qwt/src/qwt_event_pattern.o \
./visualnoc/integrator/qwt/src/qwt_graphic.o \
./visualnoc/integrator/qwt/src/qwt_interval.o \
./visualnoc/integrator/qwt/src/qwt_interval_symbol.o \
./visualnoc/integrator/qwt/src/qwt_knob.o \
./visualnoc/integrator/qwt/src/qwt_legend.o \
./visualnoc/integrator/qwt/src/qwt_legend_data.o \
./visualnoc/integrator/qwt/src/qwt_legend_label.o \
./visualnoc/integrator/qwt/src/qwt_magnifier.o \
./visualnoc/integrator/qwt/src/qwt_math.o \
./visualnoc/integrator/qwt/src/qwt_matrix_raster_data.o \
./visualnoc/integrator/qwt/src/qwt_null_paintdevice.o \
./visualnoc/integrator/qwt/src/qwt_painter.o \
./visualnoc/integrator/qwt/src/qwt_painter_command.o \
./visualnoc/integrator/qwt/src/qwt_panner.o \
./visualnoc/integrator/qwt/src/qwt_picker.o \
./visualnoc/integrator/qwt/src/qwt_picker_machine.o \
./visualnoc/integrator/qwt/src/qwt_pixel_matrix.o \
./visualnoc/integrator/qwt/src/qwt_plot.o \
./visualnoc/integrator/qwt/src/qwt_plot_abstract_barchart.o \
./visualnoc/integrator/qwt/src/qwt_plot_axis.o \
./visualnoc/integrator/qwt/src/qwt_plot_barchart.o \
./visualnoc/integrator/qwt/src/qwt_plot_canvas.o \
./visualnoc/integrator/qwt/src/qwt_plot_curve.o \
./visualnoc/integrator/qwt/src/qwt_plot_dict.o \
./visualnoc/integrator/qwt/src/qwt_plot_directpainter.o \
./visualnoc/integrator/qwt/src/qwt_plot_glcanvas.o \
./visualnoc/integrator/qwt/src/qwt_plot_grid.o \
./visualnoc/integrator/qwt/src/qwt_plot_histogram.o \
./visualnoc/integrator/qwt/src/qwt_plot_intervalcurve.o \
./visualnoc/integrator/qwt/src/qwt_plot_item.o \
./visualnoc/integrator/qwt/src/qwt_plot_layout.o \
./visualnoc/integrator/qwt/src/qwt_plot_legenditem.o \
./visualnoc/integrator/qwt/src/qwt_plot_magnifier.o \
./visualnoc/integrator/qwt/src/qwt_plot_marker.o \
./visualnoc/integrator/qwt/src/qwt_plot_multi_barchart.o \
./visualnoc/integrator/qwt/src/qwt_plot_panner.o \
./visualnoc/integrator/qwt/src/qwt_plot_picker.o \
./visualnoc/integrator/qwt/src/qwt_plot_rasteritem.o \
./visualnoc/integrator/qwt/src/qwt_plot_renderer.o \
./visualnoc/integrator/qwt/src/qwt_plot_rescaler.o \
./visualnoc/integrator/qwt/src/qwt_plot_scaleitem.o \
./visualnoc/integrator/qwt/src/qwt_plot_seriesitem.o \
./visualnoc/integrator/qwt/src/qwt_plot_shapeitem.o \
./visualnoc/integrator/qwt/src/qwt_plot_spectrocurve.o \
./visualnoc/integrator/qwt/src/qwt_plot_spectrogram.o \
./visualnoc/integrator/qwt/src/qwt_plot_svgitem.o \
./visualnoc/integrator/qwt/src/qwt_plot_textlabel.o \
./visualnoc/integrator/qwt/src/qwt_plot_tradingcurve.o \
./visualnoc/integrator/qwt/src/qwt_plot_xml.o \
./visualnoc/integrator/qwt/src/qwt_plot_zoneitem.o \
./visualnoc/integrator/qwt/src/qwt_plot_zoomer.o \
./visualnoc/integrator/qwt/src/qwt_point_3d.o \
./visualnoc/integrator/qwt/src/qwt_point_data.o \
./visualnoc/integrator/qwt/src/qwt_point_mapper.o \
./visualnoc/integrator/qwt/src/qwt_point_polar.o \
./visualnoc/integrator/qwt/src/qwt_raster_data.o \
./visualnoc/integrator/qwt/src/qwt_round_scale_draw.o \
./visualnoc/integrator/qwt/src/qwt_sampling_thread.o \
./visualnoc/integrator/qwt/src/qwt_scale_div.o \
./visualnoc/integrator/qwt/src/qwt_scale_draw.o \
./visualnoc/integrator/qwt/src/qwt_scale_engine.o \
./visualnoc/integrator/qwt/src/qwt_scale_map.o \
./visualnoc/integrator/qwt/src/qwt_scale_widget.o \
./visualnoc/integrator/qwt/src/qwt_series_data.o \
./visualnoc/integrator/qwt/src/qwt_slider.o \
./visualnoc/integrator/qwt/src/qwt_spline.o \
./visualnoc/integrator/qwt/src/qwt_symbol.o \
./visualnoc/integrator/qwt/src/qwt_system_clock.o \
./visualnoc/integrator/qwt/src/qwt_text.o \
./visualnoc/integrator/qwt/src/qwt_text_engine.o \
./visualnoc/integrator/qwt/src/qwt_text_label.o \
./visualnoc/integrator/qwt/src/qwt_thermo.o \
./visualnoc/integrator/qwt/src/qwt_transform.o \
./visualnoc/integrator/qwt/src/qwt_wheel.o \
./visualnoc/integrator/qwt/src/qwt_widget_overlay.o 

CPP_DEPS += \
./visualnoc/integrator/qwt/src/qwt_abstract_legend.d \
./visualnoc/integrator/qwt/src/qwt_abstract_scale.d \
./visualnoc/integrator/qwt/src/qwt_abstract_scale_draw.d \
./visualnoc/integrator/qwt/src/qwt_abstract_slider.d \
./visualnoc/integrator/qwt/src/qwt_analog_clock.d \
./visualnoc/integrator/qwt/src/qwt_arrow_button.d \
./visualnoc/integrator/qwt/src/qwt_clipper.d \
./visualnoc/integrator/qwt/src/qwt_color_map.d \
./visualnoc/integrator/qwt/src/qwt_column_symbol.d \
./visualnoc/integrator/qwt/src/qwt_compass.d \
./visualnoc/integrator/qwt/src/qwt_compass_rose.d \
./visualnoc/integrator/qwt/src/qwt_counter.d \
./visualnoc/integrator/qwt/src/qwt_curve_fitter.d \
./visualnoc/integrator/qwt/src/qwt_date.d \
./visualnoc/integrator/qwt/src/qwt_date_scale_draw.d \
./visualnoc/integrator/qwt/src/qwt_date_scale_engine.d \
./visualnoc/integrator/qwt/src/qwt_dial.d \
./visualnoc/integrator/qwt/src/qwt_dial_needle.d \
./visualnoc/integrator/qwt/src/qwt_dyngrid_layout.d \
./visualnoc/integrator/qwt/src/qwt_event_pattern.d \
./visualnoc/integrator/qwt/src/qwt_graphic.d \
./visualnoc/integrator/qwt/src/qwt_interval.d \
./visualnoc/integrator/qwt/src/qwt_interval_symbol.d \
./visualnoc/integrator/qwt/src/qwt_knob.d \
./visualnoc/integrator/qwt/src/qwt_legend.d \
./visualnoc/integrator/qwt/src/qwt_legend_data.d \
./visualnoc/integrator/qwt/src/qwt_legend_label.d \
./visualnoc/integrator/qwt/src/qwt_magnifier.d \
./visualnoc/integrator/qwt/src/qwt_math.d \
./visualnoc/integrator/qwt/src/qwt_matrix_raster_data.d \
./visualnoc/integrator/qwt/src/qwt_null_paintdevice.d \
./visualnoc/integrator/qwt/src/qwt_painter.d \
./visualnoc/integrator/qwt/src/qwt_painter_command.d \
./visualnoc/integrator/qwt/src/qwt_panner.d \
./visualnoc/integrator/qwt/src/qwt_picker.d \
./visualnoc/integrator/qwt/src/qwt_picker_machine.d \
./visualnoc/integrator/qwt/src/qwt_pixel_matrix.d \
./visualnoc/integrator/qwt/src/qwt_plot.d \
./visualnoc/integrator/qwt/src/qwt_plot_abstract_barchart.d \
./visualnoc/integrator/qwt/src/qwt_plot_axis.d \
./visualnoc/integrator/qwt/src/qwt_plot_barchart.d \
./visualnoc/integrator/qwt/src/qwt_plot_canvas.d \
./visualnoc/integrator/qwt/src/qwt_plot_curve.d \
./visualnoc/integrator/qwt/src/qwt_plot_dict.d \
./visualnoc/integrator/qwt/src/qwt_plot_directpainter.d \
./visualnoc/integrator/qwt/src/qwt_plot_glcanvas.d \
./visualnoc/integrator/qwt/src/qwt_plot_grid.d \
./visualnoc/integrator/qwt/src/qwt_plot_histogram.d \
./visualnoc/integrator/qwt/src/qwt_plot_intervalcurve.d \
./visualnoc/integrator/qwt/src/qwt_plot_item.d \
./visualnoc/integrator/qwt/src/qwt_plot_layout.d \
./visualnoc/integrator/qwt/src/qwt_plot_legenditem.d \
./visualnoc/integrator/qwt/src/qwt_plot_magnifier.d \
./visualnoc/integrator/qwt/src/qwt_plot_marker.d \
./visualnoc/integrator/qwt/src/qwt_plot_multi_barchart.d \
./visualnoc/integrator/qwt/src/qwt_plot_panner.d \
./visualnoc/integrator/qwt/src/qwt_plot_picker.d \
./visualnoc/integrator/qwt/src/qwt_plot_rasteritem.d \
./visualnoc/integrator/qwt/src/qwt_plot_renderer.d \
./visualnoc/integrator/qwt/src/qwt_plot_rescaler.d \
./visualnoc/integrator/qwt/src/qwt_plot_scaleitem.d \
./visualnoc/integrator/qwt/src/qwt_plot_seriesitem.d \
./visualnoc/integrator/qwt/src/qwt_plot_shapeitem.d \
./visualnoc/integrator/qwt/src/qwt_plot_spectrocurve.d \
./visualnoc/integrator/qwt/src/qwt_plot_spectrogram.d \
./visualnoc/integrator/qwt/src/qwt_plot_svgitem.d \
./visualnoc/integrator/qwt/src/qwt_plot_textlabel.d \
./visualnoc/integrator/qwt/src/qwt_plot_tradingcurve.d \
./visualnoc/integrator/qwt/src/qwt_plot_xml.d \
./visualnoc/integrator/qwt/src/qwt_plot_zoneitem.d \
./visualnoc/integrator/qwt/src/qwt_plot_zoomer.d \
./visualnoc/integrator/qwt/src/qwt_point_3d.d \
./visualnoc/integrator/qwt/src/qwt_point_data.d \
./visualnoc/integrator/qwt/src/qwt_point_mapper.d \
./visualnoc/integrator/qwt/src/qwt_point_polar.d \
./visualnoc/integrator/qwt/src/qwt_raster_data.d \
./visualnoc/integrator/qwt/src/qwt_round_scale_draw.d \
./visualnoc/integrator/qwt/src/qwt_sampling_thread.d \
./visualnoc/integrator/qwt/src/qwt_scale_div.d \
./visualnoc/integrator/qwt/src/qwt_scale_draw.d \
./visualnoc/integrator/qwt/src/qwt_scale_engine.d \
./visualnoc/integrator/qwt/src/qwt_scale_map.d \
./visualnoc/integrator/qwt/src/qwt_scale_widget.d \
./visualnoc/integrator/qwt/src/qwt_series_data.d \
./visualnoc/integrator/qwt/src/qwt_slider.d \
./visualnoc/integrator/qwt/src/qwt_spline.d \
./visualnoc/integrator/qwt/src/qwt_symbol.d \
./visualnoc/integrator/qwt/src/qwt_system_clock.d \
./visualnoc/integrator/qwt/src/qwt_text.d \
./visualnoc/integrator/qwt/src/qwt_text_engine.d \
./visualnoc/integrator/qwt/src/qwt_text_label.d \
./visualnoc/integrator/qwt/src/qwt_thermo.d \
./visualnoc/integrator/qwt/src/qwt_transform.d \
./visualnoc/integrator/qwt/src/qwt_wheel.d \
./visualnoc/integrator/qwt/src/qwt_widget_overlay.d 


# Each subdirectory must supply rules for building sources it contributes
visualnoc/integrator/qwt/src/%.o: ../visualnoc/integrator/qwt/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -D__GXX_EXPERIMENTAL_CXX0X__ -O0 -g3 -Wall -c -fmessage-length=0 -std=c++11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


