
include ../../Makefile.include

# path to store .obj, .cxx, and .so
MODULE := engine

# swig module
SWIG_MODULE := esy_engine

# python files to copy to module path
PYTHON_SRC := py_esy_engine.py \
              __init__.py

include ../../Makefile.rule
